import kontraBuilds from "../../data/kontra-builds.json";
import type { Tier } from "./kontra/types";

export type BuildPreset = {
  /** Display name shown on the button. */
  name: string;
  /** Stable slug id, unique within the class. */
  id: string;
  /** Dark Humility tier letter. */
  tier: Tier;
  /** Class this preset belongs to. */
  className: string;
  /** Skill names matching `character.character.skills[].name`. ALL of these
   *  must be present at the skill-filter minLevel for a character to match. */
  skills: string[];
  /** DH sheet rows that fed this preset (merged variants list more than one). */
  sources: string[];
};

export type BuildPresetsByClass = Record<string, BuildPreset[]>;

/** Build presets sourced from the Dark Humility tier list, grouped by class
 *  and sorted best tier first. Regenerated by scripts/build-kontra-snapshot.ts. */
export const BUILD_PRESETS = kontraBuilds as BuildPresetsByClass;

/** Default minLevel used when a preset populates the skill filter.
 *  20 is the standard "this is actually the build, not a 1-pt synergy" mark. */
export const PRESET_MIN_LEVEL = 20;

/**
 * True if the current skill-filter set exactly matches the preset's skill
 * list (by name, order-independent). Used to visually mark the active preset.
 */
export function isPresetActive(
  currentSkillNames: string[],
  preset: Pick<BuildPreset, "skills">,
): boolean {
  if (currentSkillNames.length !== preset.skills.length) return false;
  const present = new Set(currentSkillNames);
  return preset.skills.every((n) => present.has(n));
}
